name: CICD

on:
  push:
    branches:
      - master
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    name: Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v3

    - name: Convert repository name to lowercase
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Sign into GitHub Container Registry
      run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

    - name: Build container image latest version
      run: docker build --progress tty -t ghcr.io/${REPO}:${{ github.sha }} -t ghcr.io/${REPO}:unstable .

    - name: Push image to GitHub Container Registry
      run: |
        docker push ghcr.io/${REPO}:${{ github.sha }}
        docker push ghcr.io/${REPO}:unstable

    - name: Push release image to GitHub Container Registry
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        docker tag ghcr.io/${REPO}:${{ github.ref }} ghcr.io/${REPO}:${{ github.ref_name }}
        docker tag ghcr.io/${REPO}:${{ github.ref }} ghcr.io/${REPO}:stable
        docker tag ghcr.io/${REPO}:${{ github.ref }} ghcr.io/${REPO}:latest
        docker push ghcr.io/${REPO}:${{ github.ref_name }}
        docker push ghcr.io/${REPO}:stable
        docker push ghcr.io/${REPO}:latest
